# Sample Makefile to test theme in VSCode
.PHONY: all clean test

all: test

test:
	@echo "Testing Dragonball theme in VSCode..."
	@echo "If you see this output styled, your theme is working!"

clean:
	@echo "Cleaning up test artifacts (none in this sample)."